### ISSUE TITLE
no retry on initial connection

### ISSUE THREAD

**Issue by brianmay** [gausby/tortoise#46]
When trying to establish an initial connection, tortoise will die immediately with an error if the connection cannot be established, e.g. due to networking not being available (yet).

```
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, Tortoise.Connection, {{:with_clause, {:error, :nxdomain}}, [{Tortoise.Connection, :do_connect, 2, [file: 'lib/tortoise/connection.ex', line: 340]}, {Tortoise.Connection, :init, 1, [file: 'lib/tortoise/connection.ex', line: 196]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 365]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 333]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}}
```

This is an issue, as I am attempting to use tortoise in a [nerves](https://hexdocs.pm/nerves/getting-started.html) project, and tortoise often is started before the networking is established. Ideally tortoise would wait and retry (even better with back-off as in #44) instead of crashing.

**Comment by gausby** [comment]
Good catch. I will give it some thoughts, it should definitely be able to handle that scenario.

If you wanna give it a shot I can (try to) answer all your questions; otherwise I can make an attempt during the week to solve this.

For the tests I figure that a custom `Tortoise.Transport` that returns the error codes would be helpful for testing these scenarios.

**Comment by brianmay** [comment]
I am wondering if `Tortise.Connection.init` should send itself a `:renew_connection` message instead of trying to connect itself?

Also the do_attempt_reconnect could call `Process.send_after` with some time delay for each failure to connect if I understood this correctly.

One detail I am unsure of, are there any applications that might desire early failure if it can't connect?

**Comment by gausby** [comment]
> I am wondering if Tortise.Connection.init should send itself a :renew_connection message instead of trying to connect itself?

We have to make sure the `Tortoise.Connection.init/1` will return a reply and enter the process loop, because we need to answer in a short amount of time—otherwise the supervisor could kill the process for a retry because it assume it is hanging. `Process.send_after` would be the way to go here.

> One detail I am unsure of, are there any applications that might desire early failure if it can't connect?

I think a configuration option where the user can specify `reconnect_timeout` or `reconnect_interval` would be useful, as well as a `maxiumum_reconnect_retries`.

One thing I have to look into is alarm_handlers, because in some systems I could imagine an operator logging on to the application and updating the server-config—which will make it possible to change the server config on the fly, and will require us to expose a `Tortoise.Connection.update_config/2`…I have to give this some thought, because I don't think the user should be able to update the *handler*, because it has user defined state—but if we choose to go down that route we should consider if the new handler would inherit the state from the previous handler. Stuff to think about. I can see scenarios where one would like the system to fail instantly if it cannot make the initial connection, so I think the way to go is to make this a configuration option.

**Comment by gausby** [comment]
Just a heads up; I got a local development branch where I have build a GenServer based `Tortoise.Transport`, which I can give a script of events—such as `{:expect package}`, `{dispatch, package}`, `{refute_connection, reason}`, etc. It implements the same behaviour as the `Tortoise.Transport.Tcp/SSL` transports, so it should be fairly safe if I change the behaviour…the compiler should complain if I don't implement the correct functions.

Using it I've made it connect to the broker, and I've made a test that target the scenario where it hit the `{:error, :econnrefused}`-branch. Using this transport I should be able to test all the error cases. I have to go to bed now, but I will polish it tomorrow evening to morrow evening (if time permits) and then I will push it.

Just to let you know I am working on the problem :)

**Comment by brianmay** [comment]
Thanks!

**Comment by gausby** [comment]
It might take me some days to finish up with the retry handling. In the meantime, have you looked into this: https://github.com/nerves-project/nerves_network ?

There is also an article by Chris Freeze describe how to work with network interfaces in Nerves. https://dockyard.com/blog/2018/06/13/all-systems-go-creating-your-own-startup-checks-with-nerves

Perhaps that is helpful until I get around to fix this :)

**Comment by brianmay** [comment]
Thanks for the links.

**Comment by gausby** [comment]
About to release 0.4.0; this should solve the error with no reconnect on `{:error, :nxdomain}`. I have made it easy to add more error reasons that should/could get handled by just reconnecting (with a backoff), so more will get added in the future—I just think it would be unwise to attempt a reconnect for all connection errors, because some of them should get handled by improving the configuration.

Please let me know if 0.4.0 solves your problem; and feel free to close the issue if it does :)

**Comment by brianmay** [comment]
So far looks good to me. Now my project is crashing where I expect it to crash :-).
