### ISSUE TITLE
how to setup ssl without certificate and key? what are their default values?

### ISSUE THREAD

**Issue by zentechlinhnguyen** [gausby/tortoise#60]

**Comment by gausby** [comment]
The `Tortoise.Transport.SSL` transport will take an opts field, and its default opts is `@default_opts [verify: :verify_peer]`.

The transport uses the Erlang `:ssl` module, please refer to the documentation for and user guide in the Erlang documentation:

  - http://erlang.org/doc/apps/ssl/ssl_introduction.html
  - http://erlang.org/doc/man/ssl.html#connect-3

**Comment by voltone** [comment]
Since Erlang does not come with a CA trust store, you're going to want to add one in order for server certificate verification to work. You can put a file with the root CA used by your server in your project's `priv` directory, or add the [certifi](https://hex.pm/packages/certifi) package as a dependency, then configure Tortoise like this:

```elixir
server: {
  host: mqtt_server,
  port: mqtt_port,
  cacertfile: :certifi.cacertfile()
}
```

Alternatively, for testing purposes, you can disable server certificate verification by passing `verify: :verify_none` in the server options. In that case there is no need for CA certificates, but you don't get the protections against impersonation or MitM attacks.

**Comment by voltone** [comment]
I updated the README file with these instructions in #65

**Comment by gausby** [comment]
@zentechlinhnguyen does the additions to the documentation in #65 answer your question ?

**Comment by gausby** [comment]
Closing this issue; it seems inactive.
