### ISSUE TITLE
Cannot set clean_session false when start a connection

### ISSUE THREAD

**Issue by 250lth** [gausby/tortoise#87]
I want to set clean_session false for the offline messages of an mq, but it seems that clean_session is set true and I cannot edit it.
```elixir
connect = %Package.Connect{
    client_id: client_id,
    user_name: Keyword.get(connection_opts, :user_name),
    password: Keyword.get(connection_opts, :password),
    keep_alive: Keyword.get(connection_opts, :keep_alive, 60),
    will: Keyword.get(connection_opts, :will),
    # if we re-spawn from here it means our state is gone
    clean_session: true #HERE
}
```

**Comment by 250lth** [comment]
I'm using this client as a customer service message center. 
It subscribes both customer's and agent's messages and using `handle_message` to choose where to send a message. It also stores all the messages it got.
If `clean_session` can be set false, when my message center is down or we restart it, it can also get the offline messages. But when `clean_session` is true, when restart, offline messages cannot be solved.

**Comment by gausby** [comment]
I am not sure I fully understand your setup here, but if I understand it right I would suggest that you move the persisted messages outside of the tortoise handler state. The session state relates to in flight messages and what subscriptions the client currently have—as the comment in the code says: «if we re-spawn from here it means our state is gone».

You can supervise your Tortoise client instance with the process that keep the persisted messages; please have a look at the «Supervising a connection» in the [Connection Supervision](https://hexdocs.pm/tortoise/connection_supervision.html#content) documentation.

Would that work for you ?

**Comment by 250lth** [comment]
Sorry, it does not work for me.
The mqtt broker we use only keeps un-acked messages and resend them if the connection's clean_session is false. It gets the clean_session state of the connection when the connection is started. So we must set it when start the connection.
Most of the mqtt clients can set the `clean_session` state when start connection, such as Mqtt.js, Eclipse Paho Java Client.

**Comment by gausby** [comment]
What is the name of this broker?

**Comment by 250lth** [comment]
It is Aliyun LMQ, from China.
[Aliyun LMQ Doc](https://help.aliyun.com/document_detail/42420.html?spm=a2c4g.11186623.6.699.2c3d5dbfsJLjOP)
Maybe you cannot read it. But at the bottom of that page, it says, only when qos=1 and clean_session=false can we get offline messages.

**Comment by gausby** [comment]
The way a connection in Tortoise works is as follows:

- A client lives inside of a process; when spawned it will connect to the broker using clean_state=true
- If the connect is successful it will spawn a couple of processes, amongst them a process that deal with inflight messages
- When the connection is broken the client will attempt to reestablish it by reconnecting with clean_state=false—the packages in the *known session state*, kept in the inflight process, will then get retransmitted

This is (best to my knowledge) in line with the MQTT protocol. Unless we store state to disk we cannot reconnect with a state present because we have none. If the client id exist on the server when we perform the cold start the server and the client would be out of sync, and the inflight process would most likely crash.

So, sorry, it seems to me you are asking for something that is not in line with the specification. If I made it possible to set the session_state manually when connecting I would have to explain why I stray away from the protocol in the documentation.

**Comment by imetallica** [comment]
Sorry to bother you with this again but I think there is a potential problem with the default approach.

Imagine that I'm running on Heroku and that it does restart the dynos my app is running. This means that, when my app boots up, I've lost all my messages if you set `clean_state: true` on the first connection.

Other use case would be updating an application that's build with docker images, running on kubernetes, or scaling up a system. Some of these brokers have load balacing between multiple clients with same id - VerneMQ is one of them.

I know that the correct way would be to have systems being booted up and connecting with `clean_state=true`, but reality is quite different. Stuff goes down due to energy outages, missconfiguration, accidental power switching, etc, etc... I think adding the possibility to choose the `clean_state` for the initial connection is a good addition to the library.

**Comment by ryanwinchester** [comment]
@gausby I'm using https://github.com/vernemq/vernemq and I'm pretty sure that if `clean session = true` then when I am offline I will not get any of the messages to the broker that I wanted to be subscribed to.
